# -*- coding: utf-8 -*-
"""groceries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zg9xQ3xDm-lP4bxsQOKKFm0O4kK3nJp_

# Assignment 4: Association Rules

### Problem Statement 2:
The Departmental Store, has gathered the data of the products it sells on a Daily basis.
Using Association Rules concepts, provide the insights on the rules and the plots.

### **Business Objective:**
The objective for the Departmental Store is to use the Association Rule Mining technique to uncover patterns and relationships between products sold on a daily basis. By identifying which products are frequently bought together, the store can:

- Optimize product placement.

- Design targeted promotions and bundle offers.

- Improve inventory management to ensure that complementary items are stocked together.

The ultimate goal is to increase sales by understanding customer buying patterns and making informed business decisions based on the identified associations.
"""

import pandas as pd
df=pd.read_csv('groceries.csv', on_bad_lines='skip')
df.head()

transactions=[]
transactions.append(df.keys().tolist())

transactions.extend(df.values.tolist())

transactions

#removing nan values from the list
transactions=[[item for item in sublist if not pd.isna(item)] for sublist in transactions]
transactions

#Step 1: convert the data in a format suitable for apriori
from mlxtend.preprocessing import TransactionEncoder
te=TransactionEncoder()
te_ary=te.fit(transactions).transform(transactions)
df=pd.DataFrame(te_ary, columns=te.columns_)
df

df=df.astype(int)
df

#step 2: apply the apriori algorithm to find frequent itemsets
from mlxtend.frequent_patterns import apriori,association_rules
frequent_itemsets=apriori(df,min_support=0.07,use_colnames=True)

#step 3: Generate association rules from the frequent itemsets
rules=association_rules(frequent_itemsets,metric='lift',min_threshold=0.05)

# step 4: output the results
print("frequent itemsets:")
print(frequent_itemsets)
print("\nAssociation rules:")
print(rules)

transactions

